// Do NOT change this file format without updating the parsing logic in
// BluetoothService.java

AddressBlacklist=

// Blacklisting by Exact Name:
ExactNameBlacklist=

// Blacklisting by Partial Name (if name starts with)
PartialNameBlacklist=

// Fixed PIN keyboard blacklist. Keyboards should have variable PIN
// The keyboards below have a fixed PIN of 0000, so we will auto pair.
// Note the reverse logic in this case compared to other's in this file
// where its a blacklist for not auto pairing.
FixedPinZerosKeyboardBlacklist=00:0F:F6

// Blacklisting by addition of the address during usage
