// Do NOT change this file format without updating the parsing logic in
// the modules that use this file (listed below):
//       android_bluetooth_ScoSocket.cpp

// Module,Type,Value List,Parameter List,  //Comment
